package com.example.focusflight.util

// GENERATED by tools/gen_airport_timezones.py from app/src/main/assets/flights.db - do not edit
// by hand; re-run the script when the airport data changes. See FlightClock.kt for how it is used.

internal class ZoneAnchor(val lat: Double, val lon: Double, val zoneId: String)

/** Countries whose airports all keep one clock. */
internal val SINGLE_ZONE_COUNTRIES: Map<String, String> = hashMapOf(
    "AE" to "Asia/Dubai",
    "AF" to "Asia/Kabul",
    "AG" to "America/Antigua",
    "AI" to "America/Anguilla",
    "AL" to "Europe/Tirane",
    "AM" to "Asia/Yerevan",
    "AO" to "Africa/Luanda",
    "AQ" to "America/Punta_Arenas",
    "AR" to "America/Argentina/Cordoba",
    "AS" to "Pacific/Pago_Pago",
    "AT" to "Europe/Vienna",
    "AW" to "America/Aruba",
    "AZ" to "Asia/Baku",
    "BA" to "Europe/Sarajevo",
    "BB" to "America/Barbados",
    "BD" to "Asia/Dhaka",
    "BE" to "Europe/Brussels",
    "BF" to "Africa/Ouagadougou",
    "BG" to "Europe/Sofia",
    "BH" to "Asia/Bahrain",
    "BI" to "Africa/Bujumbura",
    "BJ" to "Africa/Porto-Novo",
    "BL" to "America/St_Barthelemy",
    "BM" to "Atlantic/Bermuda",
    "BN" to "Asia/Brunei",
    "BO" to "America/La_Paz",
    "BQ" to "America/Kralendijk",
    "BS" to "America/Nassau",
    "BT" to "Asia/Thimphu",
    "BW" to "Africa/Gaborone",
    "BY" to "Europe/Minsk",
    "BZ" to "America/Belize",
    "CC" to "Indian/Cocos",
    "CF" to "Africa/Bangui",
    "CG" to "Africa/Brazzaville",
    "CH" to "Europe/Zurich",
    "CI" to "Africa/Abidjan",
    "CK" to "Pacific/Rarotonga",
    "CM" to "Africa/Douala",
    "CO" to "America/Bogota",
    "CR" to "America/Costa_Rica",
    "CU" to "America/Havana",
    "CV" to "Atlantic/Cape_Verde",
    "CW" to "America/Curacao",
    "CX" to "Indian/Christmas",
    "CY" to "Asia/Famagusta",
    "CZ" to "Europe/Prague",
    "DE" to "Europe/Berlin",
    "DJ" to "Africa/Djibouti",
    "DK" to "Europe/Copenhagen",
    "DM" to "America/Dominica",
    "DO" to "America/Santo_Domingo",
    "DZ" to "Africa/Algiers",
    "EE" to "Europe/Tallinn",
    "EG" to "Africa/Cairo",
    "EH" to "Africa/El_Aaiun",
    "ER" to "Africa/Asmara",
    "ET" to "Africa/Addis_Ababa",
    "FI" to "Europe/Helsinki",
    "FJ" to "Pacific/Fiji",
    "FK" to "Atlantic/Stanley",
    "FO" to "Atlantic/Faroe",
    "FR" to "Europe/Paris",
    "GA" to "Africa/Libreville",
    "GB" to "Europe/London",
    "GD" to "America/Grenada",
    "GE" to "Asia/Tbilisi",
    "GF" to "America/Cayenne",
    "GG" to "Europe/Guernsey",
    "GH" to "Africa/Accra",
    "GI" to "Europe/Gibraltar",
    "GM" to "Africa/Banjul",
    "GN" to "Africa/Conakry",
    "GP" to "America/Guadeloupe",
    "GQ" to "Africa/Malabo",
    "GR" to "Europe/Athens",
    "GT" to "America/Guatemala",
    "GU" to "Pacific/Guam",
    "GW" to "Africa/Bissau",
    "GY" to "America/Guyana",
    "HK" to "Asia/Hong_Kong",
    "HN" to "America/Tegucigalpa",
    "HR" to "Europe/Zagreb",
    "HT" to "America/Port-au-Prince",
    "HU" to "Europe/Budapest",
    "IE" to "Europe/Dublin",
    "IL" to "Asia/Jerusalem",
    "IM" to "Europe/Isle_of_Man",
    "IN" to "Asia/Kolkata",
    "IQ" to "Asia/Baghdad",
    "IR" to "Asia/Tehran",
    "IS" to "Atlantic/Reykjavik",
    "IT" to "Europe/Rome",
    "JE" to "Europe/Jersey",
    "JM" to "America/Jamaica",
    "JO" to "Asia/Amman",
    "JP" to "Asia/Tokyo",
    "KE" to "Africa/Nairobi",
    "KG" to "Asia/Bishkek",
    "KH" to "Asia/Phnom_Penh",
    "KM" to "Indian/Comoro",
    "KN" to "America/St_Kitts",
    "KP" to "Asia/Pyongyang",
    "KR" to "Asia/Seoul",
    "KW" to "Asia/Kuwait",
    "KY" to "America/Cayman",
    "KZ" to "Asia/Almaty",
    "LA" to "Asia/Vientiane",
    "LB" to "Asia/Beirut",
    "LC" to "America/St_Lucia",
    "LK" to "Asia/Colombo",
    "LR" to "Africa/Monrovia",
    "LS" to "Africa/Maseru",
    "LT" to "Europe/Vilnius",
    "LU" to "Europe/Luxembourg",
    "LV" to "Europe/Riga",
    "LY" to "Africa/Tripoli",
    "MA" to "Africa/Casablanca",
    "MC" to "Europe/Monaco",
    "MD" to "Europe/Chisinau",
    "ME" to "Europe/Podgorica",
    "MF" to "America/Marigot",
    "MG" to "Indian/Antananarivo",
    "MH" to "Pacific/Majuro",
    "MK" to "Europe/Skopje",
    "ML" to "Africa/Bamako",
    "MM" to "Asia/Yangon",
    "MO" to "Asia/Macau",
    "MP" to "Pacific/Saipan",
    "MQ" to "America/Martinique",
    "MR" to "Africa/Nouakchott",
    "MS" to "America/Montserrat",
    "MT" to "Europe/Malta",
    "MU" to "Indian/Mauritius",
    "MV" to "Indian/Maldives",
    "MW" to "Africa/Blantyre",
    "MY" to "Asia/Kuching",
    "MZ" to "Africa/Maputo",
    "NA" to "Africa/Windhoek",
    "NC" to "Pacific/Noumea",
    "NE" to "Africa/Niamey",
    "NF" to "Pacific/Norfolk",
    "NG" to "Africa/Lagos",
    "NI" to "America/Managua",
    "NL" to "Europe/Amsterdam",
    "NO" to "Europe/Oslo",
    "NP" to "Asia/Kathmandu",
    "NR" to "Pacific/Nauru",
    "NU" to "Pacific/Niue",
    "OM" to "Asia/Muscat",
    "PA" to "America/Panama",
    "PE" to "America/Lima",
    "PH" to "Asia/Manila",
    "PK" to "Asia/Karachi",
    "PL" to "Europe/Warsaw",
    "PM" to "America/Miquelon",
    "PR" to "America/Puerto_Rico",
    "PW" to "Pacific/Palau",
    "PY" to "America/Asuncion",
    "QA" to "Asia/Qatar",
    "RE" to "Indian/Reunion",
    "RO" to "Europe/Bucharest",
    "RS" to "Europe/Belgrade",
    "RW" to "Africa/Kigali",
    "SA" to "Asia/Riyadh",
    "SB" to "Pacific/Guadalcanal",
    "SC" to "Indian/Mahe",
    "SD" to "Africa/Khartoum",
    "SE" to "Europe/Stockholm",
    "SG" to "Asia/Singapore",
    "SH" to "Atlantic/St_Helena",
    "SI" to "Europe/Ljubljana",
    "SK" to "Europe/Bratislava",
    "SL" to "Africa/Freetown",
    "SN" to "Africa/Dakar",
    "SO" to "Africa/Mogadishu",
    "SR" to "America/Paramaribo",
    "SS" to "Africa/Juba",
    "ST" to "Africa/Sao_Tome",
    "SV" to "America/El_Salvador",
    "SX" to "America/Lower_Princes",
    "SY" to "Asia/Damascus",
    "SZ" to "Africa/Mbabane",
    "TC" to "America/Grand_Turk",
    "TD" to "Africa/Ndjamena",
    "TG" to "Africa/Lome",
    "TH" to "Asia/Bangkok",
    "TJ" to "Asia/Dushanbe",
    "TL" to "Asia/Dili",
    "TM" to "Asia/Ashgabat",
    "TN" to "Africa/Tunis",
    "TO" to "Pacific/Tongatapu",
    "TR" to "Europe/Istanbul",
    "TT" to "America/Port_of_Spain",
    "TV" to "Pacific/Funafuti",
    "TW" to "Asia/Taipei",
    "TZ" to "Africa/Dar_es_Salaam",
    "UG" to "Africa/Kampala",
    "UM" to "Pacific/Wake",
    "UY" to "America/Montevideo",
    "UZ" to "Asia/Samarkand",
    "VC" to "America/St_Vincent",
    "VE" to "America/Caracas",
    "VG" to "America/Tortola",
    "VI" to "America/St_Thomas",
    "VN" to "Asia/Ho_Chi_Minh",
    "VU" to "Pacific/Efate",
    "WF" to "Pacific/Wallis",
    "WS" to "Pacific/Apia",
    "XK" to "Europe/Belgrade",
    "YE" to "Asia/Aden",
    "YT" to "Indian/Mayotte",
    "ZA" to "Africa/Johannesburg",
    "ZM" to "Africa/Lusaka",
    "ZW" to "Africa/Harare"
)

/** Multi-zone countries: the zone of the nearest anchor airport is the airport's zone. */
internal val ZONE_ANCHORS: Map<String, List<ZoneAnchor>> = hashMapOf(
    "AU" to listOf(
        ZoneAnchor(-10.946, 142.455, "Australia/Brisbane"), // ABM
        ZoneAnchor(-36.067, 146.959, "Australia/Sydney"), // ABX
        ZoneAnchor(-34.948, 138.533, "Australia/Adelaide"), // ADL
        ZoneAnchor(-34.943, 117.809, "Australia/Perth"), // ALH
        ZoneAnchor(-23.807, 133.903, "Australia/Darwin"), // ASP
        ZoneAnchor(-23.566, 145.302, "Australia/Brisbane"), // BCI
        ZoneAnchor(-24.346, 139.46, "Australia/Brisbane"), // BEU
        ZoneAnchor(-17.949, 122.228, "Australia/Perth"), // BME
        ZoneAnchor(-28.833, 153.561, "Australia/Sydney"), // BNK
        ZoneAnchor(-29.038, 134.722, "Australia/Adelaide"), // CPD
        ZoneAnchor(-12.415, 130.882, "Australia/Darwin"), // DRW
        ZoneAnchor(-23.87, 151.225, "Australia/Brisbane"), // GLT
        ZoneAnchor(-12.269, 136.818, "Australia/Darwin"), // GOV
        ZoneAnchor(-15.778, 128.708, "Australia/Perth"), // KNX
        ZoneAnchor(-17.457, 140.83, "Australia/Brisbane"), // KRB
        ZoneAnchor(-31.538, 159.075, "Australia/Lord_Howe"), // LDH
        ZoneAnchor(-26.593, 153.083, "Australia/Brisbane"), // MCY
        ZoneAnchor(-34.229, 142.086, "Australia/Melbourne"), // MQL
        ZoneAnchor(-38.318, 141.471, "Australia/Melbourne"), // PTJ
        ZoneAnchor(-32.001, 141.472, "Australia/Broken_Hill"), // BHQ
        ZoneAnchor(-30.039, 145.952, "Australia/Sydney"), // BRK
        ZoneAnchor(-28.03, 145.622, "Australia/Brisbane"), // CMA
        ZoneAnchor(-18.337, 130.638, "Australia/Darwin"), // HOK
        ZoneAnchor(-37.744, 140.781, "Australia/Adelaide") // MGB
    ),
    "BR" to listOf(
        ZoneAnchor(-19.563, -46.96, "America/Sao_Paulo"), // AAX
        ZoneAnchor(-9.866, -56.106, "America/Cuiaba"), // AFL
        ZoneAnchor(-3.253, -52.254, "America/Santarem"), // ATM
        ZoneAnchor(-0.981, -62.919, "America/Manaus"), // BAZ
        ZoneAnchor(-21.247, -56.452, "America/Campo_Grande"), // BYO
        ZoneAnchor(-25.0, -53.501, "America/Sao_Paulo"), // CAC
        ZoneAnchor(-7.6, -72.77, "America/Rio_Branco"), // CZS
        ZoneAnchor(-3.855, -32.423, "America/Noronha"), // FEN
        ZoneAnchor(-3.776, -38.532, "America/Fortaleza"), // FOR
        ZoneAnchor(-7.149, -34.951, "America/Fortaleza"), // JPA
        ZoneAnchor(-10.291, -48.357, "America/Araguaina"), // PMW
        ZoneAnchor(-4.256, -69.936, "America/Manaus") // TBT
    ),
    "CA" to listOf(
        ZoneAnchor(60.819, -78.149, "America/Toronto"), // AKV
        ZoneAnchor(49.291, -123.117, "America/Vancouver"), // CXH
        ZoneAnchor(56.052, -95.619, "America/Winnipeg"), // ILF
        ZoneAnchor(68.223, -135.006, "America/Inuvik"), // LAK
        ZoneAnchor(52.709, -88.542, "America/Toronto"), // SUR
        ZoneAnchor(52.894, -89.289, "America/Winnipeg"), // WNN
        ZoneAnchor(73.006, -85.046, "America/Rankin_Inlet"), // YAB
        ZoneAnchor(51.392, -56.083, "America/St_Johns"), // YAY
        ZoneAnchor(68.536, -89.806, "America/Cambridge_Bay"), // YBB
        ZoneAnchor(49.133, -68.204, "America/Toronto"), // YBC
        ZoneAnchor(59.561, -108.481, "America/Regina"), // YBE
        ZoneAnchor(64.299, -96.078, "America/Rankin_Inlet"), // YBK
        ZoneAnchor(51.444, -57.185, "America/Blanc-Sablon"), // YBX
        ZoneAnchor(54.304, -110.744, "America/Edmonton"), // YBY
        ZoneAnchor(47.991, -66.33, "America/Moncton"), // YCL
        ZoneAnchor(70.486, -68.517, "America/Iqaluit"), // YCY
        ZoneAnchor(64.043, -139.128, "America/Dawson"), // YDA
        ZoneAnchor(49.208, -57.396, "America/St_Johns"), // YDF
        ZoneAnchor(58.422, -130.032, "America/Vancouver"), // YDL
        ZoneAnchor(56.551, -61.682, "America/Goose_Bay"), // YDP
        ZoneAnchor(56.019, -87.676, "America/Toronto"), // YER
        ZoneAnchor(64.191, -114.077, "America/Edmonton"), // YFJ
        ZoneAnchor(61.76, -121.237, "America/Inuvik"), // YFS
        ZoneAnchor(48.775, -64.482, "America/Toronto"), // YGP
        ZoneAnchor(47.425, -61.779, "America/Halifax"), // YGR
        ZoneAnchor(69.365, -81.816, "America/Iqaluit"), // YGT
        ZoneAnchor(76.426, -82.909, "America/Iqaluit"), // YGZ
        ZoneAnchor(70.763, -117.806, "America/Edmonton"), // YHI
        ZoneAnchor(60.84, -115.783, "America/Edmonton"), // YHY
        ZoneAnchor(72.689, -77.969, "America/Iqaluit"), // YIO
        ZoneAnchor(54.805, -66.805, "America/Toronto"), // YKL
        ZoneAnchor(50.19, -61.789, "America/Blanc-Sablon"), // YNA
        ZoneAnchor(67.571, -139.839, "America/Dawson"), // YOC
        ZoneAnchor(53.214, -105.673, "America/Regina"), // YPA
        ZoneAnchor(69.361, -124.075, "America/Inuvik"), // YPC
        ZoneAnchor(51.446, -90.214, "America/Atikokan"), // YPL
        ZoneAnchor(51.82, -93.973, "America/Winnipeg"), // YPM
        ZoneAnchor(58.767, -111.117, "America/Edmonton"), // YPY
        ZoneAnchor(53.971, -101.091, "America/Winnipeg"), // YQD
        ZoneAnchor(42.276, -82.956, "America/Toronto"), // YQG
        ZoneAnchor(60.117, -128.822, "America/Whitehorse"), // YQH
        ZoneAnchor(50.183, -86.696, "America/Toronto"), // YQN
        ZoneAnchor(53.683, -57.042, "America/Goose_Bay"), // YRF
        ZoneAnchor(66.521, -86.225, "America/Rankin_Inlet"), // YUT
        ZoneAnchor(48.071, -65.46, "America/Toronto"), // YVB
        ZoneAnchor(52.922, -66.864, "America/Goose_Bay"), // YWK
        ZoneAnchor(49.611, -115.782, "America/Edmonton"), // YXC
        ZoneAnchor(56.238, -120.74, "America/Dawson_Creek"), // YXJ
        ZoneAnchor(50.114, -91.905, "America/Winnipeg"), // YXL
        ZoneAnchor(53.884, -122.667, "America/Vancouver"), // YXS
        ZoneAnchor(64.193, -83.359, "America/Atikokan"), // YZS
        ZoneAnchor(49.056, -117.609, "America/Vancouver"), // YZZ
        ZoneAnchor(47.63, -65.739, "America/Moncton"), // ZBF
        ZoneAnchor(58.711, -65.993, "America/Toronto"), // XGR
        ZoneAnchor(58.614, -101.469, "America/Winnipeg"), // XLB
        ZoneAnchor(51.727, -91.824, "America/Winnipeg"), // YAC
        ZoneAnchor(53.47, -55.788, "America/St_Johns"), // YBI
        ZoneAnchor(69.108, -105.138, "America/Cambridge_Bay"), // YCB
        ZoneAnchor(67.816, -115.143, "America/Cambridge_Bay"), // YCO
        ZoneAnchor(50.282, -63.611, "America/Toronto"), // YGV
        ZoneAnchor(58.277, -104.082, "America/Regina"), // YNL
        ZoneAnchor(56.227, -117.447, "America/Edmonton"), // YPE
        ZoneAnchor(48.372, -89.324, "America/Toronto"), // YQT
        ZoneAnchor(64.23, -76.527, "America/Iqaluit") // YTE
    ),
    "CD" to listOf(
        ZoneAnchor(4.253, 20.975, "Africa/Kinshasa"), // BDT
        ZoneAnchor(1.566, 30.221, "Africa/Lubumbashi"), // BUX
        ZoneAnchor(-5.9, 22.469, "Africa/Lubumbashi"), // KGA
        ZoneAnchor(-5.036, 18.786, "Africa/Kinshasa"), // KKW
        ZoneAnchor(-4.33, 20.59, "Africa/Lubumbashi"), // PFR
        ZoneAnchor(-0.287, 20.884, "Africa/Kinshasa"), // BNB
        ZoneAnchor(0.482, 25.338, "Africa/Lubumbashi") // FKI
    ),
    "CL" to listOf(
        ZoneAnchor(-23.445, -70.445, "America/Santiago"), // ANF
        ZoneAnchor(-45.916, -71.689, "America/Coyhaique"), // BBA
        ZoneAnchor(-36.772, -73.063, "America/Santiago"), // CCP
        ZoneAnchor(-27.165, -109.421, "Pacific/Easter"), // IPC
        ZoneAnchor(-42.34, -73.716, "America/Santiago") // MHC
    ),
    "CN" to listOf(
        ZoneAnchor(47.75, 88.086, "Asia/Urumqi"), // AAT
        ZoneAnchor(25.083, 104.961, "Asia/Shanghai"), // ACX
        ZoneAnchor(45.505, 123.02, "Asia/Shanghai"), // DBC
        ZoneAnchor(40.162, 94.813, "Asia/Shanghai"), // DNH
        ZoneAnchor(42.841, 93.669, "Asia/Urumqi"), // HMI
        ZoneAnchor(38.235, 85.465, "Asia/Urumqi"), // IQM
        ZoneAnchor(28.422, 92.348, "Asia/Shanghai"), // LGZ
        ZoneAnchor(32.098, 80.054, "Asia/Shanghai"), // NGQ
        ZoneAnchor(37.661, 75.289, "Asia/Urumqi") // HQL
    ),
    "EC" to listOf(
        ZoneAnchor(-2.889, -78.984, "America/Guayaquil"), // CUE
        ZoneAnchor(-0.454, -90.266, "Pacific/Galapagos") // GPS
    ),
    "ES" to listOf(
        ZoneAnchor(28.945, -13.605, "Atlantic/Canary"), // ACE
        ZoneAnchor(36.675, -4.499, "Europe/Madrid") // AGP
    ),
    "FM" to listOf(
        ZoneAnchor(5.357, 162.958, "Pacific/Kosrae"), // KSA
        ZoneAnchor(7.462, 151.843, "Pacific/Chuuk") // TKK
    ),
    "GL" to listOf(
        ZoneAnchor(65.612, -37.618, "America/Nuuk"), // AGM
        ZoneAnchor(77.489, -69.389, "America/Thule"), // NAQ
        ZoneAnchor(73.373, -56.06, "America/Nuuk") // TQA
    ),
    "ID" to listOf(
        ZoneAnchor(-0.374, 117.25, "Asia/Makassar"), // AAP
        ZoneAnchor(-3.71, 128.089, "Asia/Jayapura"), // AMQ
        ZoneAnchor(-8.132, 124.597, "Asia/Makassar"), // ARD
        ZoneAnchor(-6.901, 107.576, "Asia/Jakarta"), // BDO
        ZoneAnchor(-8.748, 115.167, "Asia/Makassar"), // DPS
        ZoneAnchor(-1.026, 114.929, "Asia/Pontianak"), // HMS
        ZoneAnchor(-8.242, 113.693, "Asia/Jakarta"), // JBB
        ZoneAnchor(-8.141, 127.91, "Asia/Jayapura"), // JIO
        ZoneAnchor(-3.295, 116.164, "Asia/Makassar"), // KBU
        ZoneAnchor(0.889, 124.034, "Asia/Makassar"), // LKM
        ZoneAnchor(1.707, 114.97, "Asia/Makassar"), // LPU
        ZoneAnchor(3.909, 108.388, "Asia/Jakarta"), // NTX
        ZoneAnchor(0.835, 112.94, "Asia/Pontianak"), // PSU
        ZoneAnchor(-2.217, 115.436, "Asia/Makassar"), // TJG
        ZoneAnchor(0.831, 127.382, "Asia/Jayapura"), // TTE
        ZoneAnchor(-3.376, 112.537, "Asia/Pontianak"), // KLP
        ZoneAnchor(-2.227, 113.943, "Asia/Pontianak") // PKY
    ),
    "KI" to listOf(
        ZoneAnchor(0.185, 173.637, "Pacific/Tarawa"), // AAK
        ZoneAnchor(1.986, -157.35, "Pacific/Kiritimati") // CXI
    ),
    "MN" to listOf(
        ZoneAnchor(46.25, 102.802, "Asia/Ulaanbaatar"), // AVK
        ZoneAnchor(47.954, 91.628, "Asia/Hovd"), // HVD
        ZoneAnchor(46.376, 96.221, "Asia/Ulaanbaatar") // LTI
    ),
    "MX" to listOf(
        ZoneAnchor(16.757, -99.753, "America/Mexico_City"), // ACA
        ZoneAnchor(27.393, -109.833, "America/Hermosillo"), // CEN
        ZoneAnchor(31.637, -106.429, "America/Ciudad_Juarez"), // CJS
        ZoneAnchor(18.505, -88.328, "America/Cancun"), // CTM
        ZoneAnchor(28.703, -105.964, "America/Chihuahua"), // CUU
        ZoneAnchor(28.026, -114.024, "America/Tijuana"), // GUB
        ZoneAnchor(25.77, -97.525, "America/Matamoros"), // MAM
        ZoneAnchor(20.93, -89.645, "America/Merida"), // MID
        ZoneAnchor(25.779, -100.107, "America/Monterrey"), // MTY
        ZoneAnchor(27.444, -99.571, "America/Matamoros"), // NLD
        ZoneAnchor(31.352, -113.305, "America/Hermosillo"), // PPE
        ZoneAnchor(27.093, -112.099, "America/Mazatlan"), // SRL
        ZoneAnchor(22.293, -97.867, "America/Monterrey"), // TAM
        ZoneAnchor(14.795, -92.37, "America/Mexico_City"), // TAP
        ZoneAnchor(32.541, -116.97, "America/Tijuana"), // TIJ
        ZoneAnchor(21.42, -104.842, "America/Mazatlan"), // TPQ
        ZoneAnchor(19.397, -102.039, "America/Mexico_City"), // UPN
        ZoneAnchor(22.895, -102.687, "America/Mexico_City"), // ZCL
        ZoneAnchor(19.145, -104.559, "America/Mexico_City"), // ZLO
        ZoneAnchor(21.041, -86.873, "America/Cancun"), // CUN
        ZoneAnchor(20.68, -105.254, "America/Mexico_City") // PVR
    ),
    "NZ" to listOf(
        ZoneAnchor(-37.012, 174.786, "Pacific/Auckland"), // AKL
        ZoneAnchor(-43.812, -176.465, "Pacific/Chatham") // CHT
    ),
    "PF" to listOf(
        ZoneAnchor(-17.353, -145.51, "Pacific/Tahiti"), // AAA
        ZoneAnchor(-9.769, -139.011, "Pacific/Marquesas"), // AUQ
        ZoneAnchor(-23.08, -134.89, "Pacific/Gambier"), // GMR
        ZoneAnchor(-14.177, -141.266, "Pacific/Tahiti") // NAU
    ),
    "PG" to listOf(
        ZoneAnchor(-7.237, 141.106, "Pacific/Port_Moresby"), // BOT
        ZoneAnchor(-5.422, 154.673, "Pacific/Bougainville"), // BUA
        ZoneAnchor(-6.271, 150.331, "Pacific/Port_Moresby"), // GMI
        ZoneAnchor(-3.044, 152.629, "Pacific/Port_Moresby") // LNV
    ),
    "PT" to listOf(
        ZoneAnchor(41.858, -6.707, "Europe/Lisbon"), // BGC
        ZoneAnchor(39.672, -31.114, "Atlantic/Azores") // CVU
    ),
    "RU" to listOf(
        ZoneAnchor(45.002, 37.347, "Europe/Moscow"), // AAQ
        ZoneAnchor(53.74, 91.385, "Asia/Krasnoyarsk"), // ABA
        ZoneAnchor(69.763, 61.556, "Europe/Moscow"), // AMV
        ZoneAnchor(46.283, 48.011, "Europe/Astrakhan"), // ASF
        ZoneAnchor(52.381, 140.449, "Asia/Vladivostok"), // BQG
        ZoneAnchor(50.425, 127.412, "Asia/Yakutsk"), // BQS
        ZoneAnchor(56.37, 101.702, "Asia/Irkutsk"), // BTK
        ZoneAnchor(70.315, 68.334, "Asia/Yekaterinburg"), // BVJ
        ZoneAnchor(55.303, 61.505, "Asia/Yekaterinburg"), // CEK
        ZoneAnchor(70.623, 147.902, "Asia/Srednekolymsk"), // CKH
        ZoneAnchor(56.09, 47.347, "Europe/Moscow"), // CSY
        ZoneAnchor(43.961, 145.685, "Asia/Magadan"), // DEE
        ZoneAnchor(45.88, 133.738, "Asia/Vladivostok"), // DLR
        ZoneAnchor(69.393, 139.89, "Asia/Vladivostok"), // DPT
        ZoneAnchor(64.735, 177.741, "Asia/Anadyr"), // DYR
        ZoneAnchor(49.19, 142.083, "Asia/Sakhalin"), // EKS
        ZoneAnchor(46.374, 44.331, "Europe/Moscow"), // ESL
        ZoneAnchor(63.687, 66.699, "Asia/Yekaterinburg"), // EYK
        ZoneAnchor(59.911, 150.72, "Asia/Magadan"), // GDX
        ZoneAnchor(64.334, 100.433, "Asia/Krasnoyarsk"), // GOY
        ZoneAnchor(51.713, 46.171, "Europe/Saratov"), // GSV
        ZoneAnchor(52.025, 113.306, "Asia/Chita"), // HTA
        ZoneAnchor(56.835, 53.462, "Europe/Samara"), // IJK
        ZoneAnchor(71.698, 128.903, "Asia/Yakutsk"), // IKS
        ZoneAnchor(54.892, 20.599, "Europe/Kaliningrad"), // KGD
        ZoneAnchor(59.8, 30.263, "Europe/Moscow"), // LED
        ZoneAnchor(52.703, 39.538, "Europe/Moscow"), // LPK
        ZoneAnchor(42.817, 47.652, "Europe/Moscow"), // MCX
        ZoneAnchor(58.181, 94.745, "Asia/Krasnoyarsk"), // MJY
        ZoneAnchor(62.535, 114.039, "Asia/Yakutsk"), // MJZ
        ZoneAnchor(66.451, 143.262, "Asia/Srednekolymsk"), // MQJ
        ZoneAnchor(55.565, 52.092, "Europe/Moscow"), // NBC
        ZoneAnchor(51.784, 143.142, "Asia/Sakhalin"), // NGK
        ZoneAnchor(69.308, 87.326, "Asia/Krasnoyarsk"), // NSK
        ZoneAnchor(55.801, 109.595, "Asia/Irkutsk"), // NZG
        ZoneAnchor(59.41, 143.057, "Asia/Vladivostok"), // OHO
        ZoneAnchor(54.963, 73.312, "Asia/Omsk"), // OMS
        ZoneAnchor(57.915, 56.021, "Asia/Yekaterinburg"), // PEE
        ZoneAnchor(65.121, 57.131, "Europe/Moscow"), // PEX
        ZoneAnchor(53.111, 45.021, "Europe/Moscow"), // PEZ
        ZoneAnchor(53.169, 158.451, "Asia/Kamchatka"), // PKC
        ZoneAnchor(51.793, 55.457, "Asia/Yekaterinburg"), // REN
        ZoneAnchor(58.06, 68.348, "Asia/Yekaterinburg"), // RMZ
        ZoneAnchor(67.792, 130.394, "Asia/Yakutsk"), // SUK
        ZoneAnchor(54.557, 55.874, "Asia/Yekaterinburg"), // UFA
        ZoneAnchor(54.27, 48.226, "Europe/Ulyanovsk"), // ULV
        ZoneAnchor(60.357, 134.435, "Asia/Khandyga"), // UMS
        ZoneAnchor(64.55, 143.115, "Asia/Ust-Nera"), // USR
        ZoneAnchor(51.809, 107.44, "Asia/Irkutsk"), // UUD
        ZoneAnchor(60.356, 102.31, "Asia/Krasnoyarsk"), // VAQ
        ZoneAnchor(67.648, 134.695, "Asia/Vladivostok") // BQJ
    ),
    "UA" to listOf(
        ZoneAnchor(48.259, 25.981, "Europe/Kyiv"), // CWC
        ZoneAnchor(45.052, 33.975, "Europe/Simferopol"), // SIP
        ZoneAnchor(48.357, 35.101, "Europe/Kyiv"), // DNK
        ZoneAnchor(46.676, 32.506, "Europe/Kyiv") // KHE
    ),
    "US" to listOf(
        ZoneAnchor(40.652, -75.443, "America/New_York"), // ABE
        ZoneAnchor(32.411, -99.682, "America/Chicago"), // ABI
        ZoneAnchor(67.106, -157.855, "America/Anchorage"), // ABL
        ZoneAnchor(35.04, -106.609, "America/Denver"), // ABQ
        ZoneAnchor(45.449, -98.422, "America/Chicago"), // ABR
        ZoneAnchor(40.978, -124.109, "America/Los_Angeles"), // ACV
        ZoneAnchor(51.884, -176.643, "America/Adak"), // ADK
        ZoneAnchor(42.053, -102.804, "America/Denver"), // AIA
        ZoneAnchor(33.308, -111.655, "America/Phoenix"), // AZA
        ZoneAnchor(35.434, -119.057, "America/Los_Angeles"), // BFL
        ZoneAnchor(36.124, -86.678, "America/Chicago"), // BNA
        ZoneAnchor(43.564, -116.223, "America/Boise"), // BOI
        ZoneAnchor(31.259, -81.466, "America/New_York"), // BQK
        ZoneAnchor(48.579, -122.824, "America/Los_Angeles"), // BYW
        ZoneAnchor(55.208, -162.725, "America/Nome"), // CDB
        ZoneAnchor(37.701, -113.099, "America/Denver"), // CDC
        ZoneAnchor(55.479, -133.148, "America/Sitka"), // CGA
        ZoneAnchor(35.035, -85.204, "America/New_York"), // CHA
        ZoneAnchor(39.998, -82.892, "America/New_York"), // CMH
        ZoneAnchor(47.168, -88.489, "America/Detroit"), // CMX
        ZoneAnchor(44.777, -89.67, "America/Chicago"), // CWA
        ZoneAnchor(37.763, -99.966, "America/Chicago"), // DDC
        ZoneAnchor(31.321, -85.45, "America/Chicago"), // DHN
        ZoneAnchor(46.798, -102.802, "America/Denver"), // DIK
        ZoneAnchor(46.842, -92.199, "America/Chicago"), // DLH
        ZoneAnchor(40.825, -115.792, "America/Los_Angeles"), // EKO
        ZoneAnchor(35.952, -112.147, "America/Phoenix"), // GCN
        ZoneAnchor(21.318, -157.926, "Pacific/Honolulu"), // HNL
        ZoneAnchor(32.688, -103.217, "America/Denver"), // HOB
        ZoneAnchor(34.636, -86.774, "America/Chicago"), // HSV
        ZoneAnchor(45.819, -88.115, "America/Menominee"), // IMT
        ZoneAnchor(32.835, -115.574, "America/Los_Angeles"), // IPL
        ZoneAnchor(46.525, -90.132, "America/Menominee"), // IWD
        ZoneAnchor(36.083, -115.152, "America/Los_Angeles"), // LAS
        ZoneAnchor(33.664, -101.823, "America/Chicago"), // LBB
        ZoneAnchor(41.126, -100.684, "America/Chicago"), // LBF
        ZoneAnchor(46.375, -117.015, "America/Los_Angeles"), // LWS
        ZoneAnchor(31.942, -102.202, "America/Chicago"), // MAF
        ZoneAnchor(44.273, -86.246, "America/Detroit"), // MBL
        ZoneAnchor(32.693, -83.649, "America/New_York"), // MCN
        ZoneAnchor(41.786, -87.752, "America/Chicago"), // MDW
        ZoneAnchor(48.258, -101.279, "America/Chicago"), // MOT
        ZoneAnchor(46.351, -87.396, "America/Detroit"), // MQT
        ZoneAnchor(46.916, -114.091, "America/Denver"), // MSO
        ZoneAnchor(41.196, -112.012, "America/Denver"), // OGD
        ZoneAnchor(38.289, -104.497, "America/Denver"), // PUB
        ZoneAnchor(41.708, -86.317, "America/Indiana/Indianapolis"), // SBN
        ZoneAnchor(38.171, -85.735, "America/Kentucky/Louisville"), // SDF
        ZoneAnchor(30.401, -84.354, "America/New_York"), // TLH
        ZoneAnchor(48.261, -103.751, "America/Chicago"), // XWA
        ZoneAnchor(32.651, -114.609, "America/Phoenix"), // YUM
        ZoneAnchor(31.533, -84.196, "America/New_York"), // ABY
        ZoneAnchor(46.773, -100.747, "America/Chicago"), // BIS
        ZoneAnchor(38.545, -89.835, "America/Chicago"), // BLV
        ZoneAnchor(34.427, -103.079, "America/Denver"), // CVN
        ZoneAnchor(38.037, -87.532, "America/Chicago"), // EVV
        ZoneAnchor(47.138, -104.807, "America/Denver"), // GDV
        ZoneAnchor(34.571, -114.358, "America/Phoenix"), // HII
        ZoneAnchor(41.703, -86.821, "America/Chicago"), // MGC
        ZoneAnchor(47.705, -104.194, "America/Denver"), // SDY
        ZoneAnchor(35.218, -101.706, "America/Chicago"), // AMA
        ZoneAnchor(40.413, -86.939, "America/Indiana/Indianapolis"), // LAF
        ZoneAnchor(40.477, -88.916, "America/Chicago") // BMI
    )
)
