#!/usr/bin/env python3
"""Generates util/AirportTimeZones.kt: the IANA time zone of every airport in flights.db.

flights.db has no time zone column, and FlightClock's API takes only (lon, lat, isoCountry). This
writes a compact lookup that FlightClock resolves from exactly those inputs:

  * a country -> zone map for every country whose airports all keep the same clock, and
  * for the ~20 countries that span several zones (US, CA, RU, BR, AU, MX, ID, ...), a small set of
    anchor airports per country. A lookup picks the zone of the nearest anchor in that country.

The anchors are chosen with condensed nearest-neighbour: an airport becomes an anchor only if the
anchors so far would give it the wrong clock. The script then re-checks every airport in the
database against the generated tables and fails if any one of them would resolve to a zone with
different UTC offsets - so the output is exact for every airport the app can show.

Zones are compared by behaviour (UTC offsets across 2026-2027), not by name, so e.g. Detroit and
New York count as the same clock. java.time applies the offsets and DST rules at runtime.

Usage (needs `pip install timezonefinder`):
    python3 tools/gen_airport_timezones.py app/src/main/assets/flights.db \
        > app/src/main/java/com/silas270/blocktime/util/AirportTimeZones.kt
"""
import math
import sqlite3
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

from timezonefinder import TimezoneFinder

INSTANTS = [datetime(y, m, d, h, tzinfo=timezone.utc)
            for y in (2026, 2027) for m in range(1, 13) for d in (1, 8, 15, 22, 28) for h in (0, 12)]
_sig = {}


def signature(zone):
    if zone not in _sig:
        zi = ZoneInfo(zone)
        _sig[zone] = tuple(t.astimezone(zi).utcoffset().total_seconds() for t in INSTANTS)
    return _sig[zone]


def dist(lat1, lon1, lat2, lon2):
    la1, lo1, la2, lo2 = map(math.radians, (lat1, lon1, lat2, lon2))
    h = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 2 * math.asin(math.sqrt(min(1.0, h)))


def main(db_path):
    tf = TimezoneFinder()
    rows = sqlite3.connect(db_path).execute(
        # Same blank-country recovery as AirportRouteSqliteDataSource.countryOf (Namibia is "NA").
        "SELECT iata_code, COALESCE(NULLIF(iso_country, ''), substr(iso_region, 1, 2)), lat, lon "
        "FROM airports WHERE iata_code != '' ORDER BY iata_code").fetchall()
    by_country = defaultdict(list)
    for iata, country, lat, lon in rows:
        zone = tf.timezone_at(lat=lat, lng=lon) or tf.closest_timezone_at(lat=lat, lng=lon)
        by_country[country or ""].append((iata, round(lat, 3), round(lon, 3), zone))

    single, anchors = {}, {}
    for country, airports in sorted(by_country.items()):
        if not country:
            continue
        if len({signature(a[3]) for a in airports}) == 1:
            single[country] = Counter(a[3] for a in airports).most_common(1)[0][0]
            continue
        store = [airports[0]]
        changed = True
        while changed:
            changed = False
            for a in airports:
                nearest = min(store, key=lambda s: dist(a[1], a[2], s[1], s[2]))
                if signature(nearest[3]) != signature(a[3]):
                    store.append(a)
                    changed = True
        anchors[country] = store

    # Verify every airport resolves to the right clock from the generated tables alone.
    for country, airports in by_country.items():
        for a in airports:
            if country in single:
                got = single[country]
            elif country in anchors:
                got = min(anchors[country], key=lambda s: dist(a[1], a[2], s[1], s[2]))[3]
            else:
                continue
            assert signature(got) == signature(a[3]), (a, got)

    out = [
        "package com.silas270.blocktime.util",
        "",
        "// GENERATED by tools/gen_airport_timezones.py from app/src/main/assets/flights.db - do not edit",
        "// by hand; re-run the script when the airport data changes. See FlightClock.kt for how it is used.",
        "",
        "internal class ZoneAnchor(val lat: Double, val lon: Double, val zoneId: String)",
        "",
        "/** Countries whose airports all keep one clock. */",
        "internal val SINGLE_ZONE_COUNTRIES: Map<String, String> = hashMapOf(",
    ]
    out += [f'    "{c}" to "{z}",' for c, z in sorted(single.items())]
    out[-1] = out[-1].rstrip(",")
    out += [")", "",
            "/** Multi-zone countries: the zone of the nearest anchor airport is the airport's zone. */",
            "internal val ZONE_ANCHORS: Map<String, List<ZoneAnchor>> = hashMapOf("]
    items = sorted(anchors.items())
    for i, (country, store) in enumerate(items):
        out.append(f'    "{country}" to listOf(')
        lines = [f'        ZoneAnchor({a[1]}, {a[2]}, "{a[3]}"), // {a[0]}' for a in store]
        lines[-1] = lines[-1].replace("), //", ") //", 1)
        out += lines
        out.append("    )" + ("," if i < len(items) - 1 else ""))
    out.append(")")
    print("\n".join(out))
    print(f"single={len(single)} multi={len(anchors)} anchors={sum(map(len, anchors.values()))}", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
